using System.Collections;
using System.Collections.Generic;
using Unity.Mathematics;
using UnityEngine;

public class AntBehaviour : MonoBehaviour
{
    ACOCON MyACOCON = new ACOCON(); // The ACO Controller.
    private List<Connection> Connections = new List<Connection>(); // Connections between nodes.

    [SerializeField] private List<Connection> MyRoute = new List<Connection>(); // The route generated by the ACO algorithm.

    //[SerializeField] private List<GameObject> Waypoints = new List<GameObject>(); // Array of possible waypoints.
    [SerializeField] private List<VisGraphWaypointManager> Waypoints;


    [Space(10)] private int count = 0;

    public float defaultMoveSpeed;
    private float currentMoveSpeed;
    public float slowDownSpeed;

    private Vector3 OffSet = new Vector3(0, 0.5f, 0); // Debug line offset.


    public int priority;

    public GameObject startNode; // The Start node for any created route.
    public List<GameObject> endNode;

    private GameObject toNode; // keep track of which node we are moving 
    private GameObject fromNode; // keep track of  form which  node it is moving To toNode

    private int currentTarget;

    public int MaxPathLength; // The max length of a path created by the ACO.


    [Space(10)] private AStarManager AStarManager = new AStarManager(); // The A* manager.
    List<Connection> aStarPath = new List<Connection>(); // Array of waypoint map connections. Represents a path.
    private bool haveToReturn = true;


    private float startTime;
    [SerializeField] private int parcelCount = 3;
    private int remaningPackage;


    [SerializeField] private VehicleInfo_UI ui;
    [SerializeField] float collisionDetectionRadius = 5;


    [SerializeField] private ForwardCheck forwardCheck;


    [SerializeField] private LayerMask whatIsAnt;
    [SerializeField] private Collider[] otherAnts;


    private void Awake()
    {
        currentMoveSpeed = defaultMoveSpeed;
        remaningPackage = parcelCount;
        startTime = Time.time;
    }

    private void Start()
    {
        ui.UpdateP_Count(parcelCount);

        foreach (VisGraphWaypointManager waypoint in Waypoints)
        {
            foreach (VisGraphConnection neighbourConnection in waypoint.Connections)
            {
                Connection aConnection = new Connection();
                aConnection.SetConnection(waypoint.gameObject, neighbourConnection.ToNode, MyACOCON.GetDefaultPheromone());
                Connections.Add(aConnection);
                AStarManager.AddConnection(aConnection);
            }
        }

        if (remaningPackage > 0)
            GeneratePath(startNode, endNode[0]);
    }


    [ContextMenu("Create Path ")]
    public void CreatePath()
    {
        foreach (VisGraphWaypointManager waypoint in Waypoints)
        {
            foreach (VisGraphConnection neighbourConnection in waypoint.Connections)
            {
                Connection aConnection = new Connection();
                aConnection.SetConnection(waypoint.gameObject, neighbourConnection.ToNode, MyACOCON.GetDefaultPheromone());
                Connections.Add(aConnection);
                AStarManager.AddConnection(aConnection);
            }
        }

        if (remaningPackage > 0)
            GeneratePath(startNode, endNode[0]);
    }

    private void FixedUpdate()
    {
        if (MyRoute.Count <= 0 || parcelCount <= 0)
            return;

        HandleCollisionAvoidance();

        if (count < MyRoute.Count)
        {
            fromNode = MyRoute[count].GetFromNode();
            toNode = MyRoute[count].GetToNode();

            if (transform.position != toNode.transform.position)
            {
                ui.UpdateTime(CalculateTime());
                ui.UpdateDistance(CalculateDistance());
                ui.UpdateSpeed(currentMoveSpeed);

                transform.position = Vector3.MoveTowards(transform.position, toNode.transform.position, Time.deltaTime * currentMoveSpeed);
                Vector3 relativePos = (toNode.transform.position) - transform.position;
                transform.rotation = Quaternion.LookRotation(relativePos);
            }
            else
            {
                count++;
            }
        }
        else
        {
            count = 0;
            if (parcelCount > 0)
            {
                parcelCount--;
                ui.UpdateP_Count(parcelCount);
                Debug.Log("Decrease - 1 ");
            }

            currentTarget++;
            if (currentTarget <= endNode.Count - 1) // IF WE STILL HAVE TO DELIVER PARCEL 
            {
                GeneratePath(fromNode, endNode[currentTarget]);
            }
            else
            {
                MyRoute.Clear();
                if (!haveToReturn) return;

                haveToReturn = false;
                aStarPath = AStarManager.PathfindAStar(fromNode, startNode);
                MyRoute = aStarPath;
            }
        }
    }


    private void HandleCollisionAvoidance()
    {
        string info = "";

        otherAnts = Physics.OverlapSphere(transform.position, collisionDetectionRadius, whatIsAnt);

        foreach (var ant in otherAnts)
        {
            if (ant.gameObject == this.gameObject)
                continue;

            //IN RANGE AND FACING TO BACK OF OTHER 
            if (forwardCheck.detected)
            {
                info += $"{this.name} Slowing Down  \n";
                currentMoveSpeed = slowDownSpeed;
            }
            else
                currentMoveSpeed = defaultMoveSpeed;


            //IN RANGE AND BOTH FACING TO EACH OTHER 
            if (forwardCheck.giveSide)
            {
                AntBehaviour otherAnt = ant.GetComponent<AntBehaviour>();
                if (otherAnt)
                {
                    if (priority > otherAnt.priority)
                    {
                        MoveRight();
                    }
                    else
                    {
                        MoveLeft();
                    }

                    info += $"{this.name} Providing Path  \n";
                }
            }
            //do slow if both have same direction to move 
            //  give side if they are passing each other 
        }

        if (!string.IsNullOrEmpty(info) && hideRoutine == null)
        {
            ui.UpdateInformation(info);
            hideRoutine = StartCoroutine((HideVehicalInfo()));
        }
    }

    private Coroutine hideRoutine;

    private IEnumerator HideVehicalInfo()
    {
        yield return new WaitForSeconds(1);
        ui.HideInformationText();
        hideRoutine = null;
    }


    public void MoveRight()
    {
        Debug.Log("Moved Right  " + this.name);
    }

    public void MoveLeft()
    {
        Debug.Log("Moved Left  " + this.name);
    }


    private void GeneratePath(GameObject _startNode, GameObject _endNode)
    {
        MyRoute = MyACOCON.ACO(100, 5, Waypoints, Connections, _startNode, _endNode, MaxPathLength);

        if (MyRoute == null || MyRoute.Count == 0)
        {
            Debug.LogError("ACO returned an empty route.");
        }
    }


    private float CalculateDistance()
    {
        return currentMoveSpeed * (Time.time - startTime);
    }

    private float CalculateTime()
    {
        return Time.time - startTime;
    }


    private void OnDrawGizmos()
    {
        // Draw path.
        if (MyRoute.Count > 0)
        {
            //ACO Route
            foreach (Connection aConnection in MyRoute)
            {
                Gizmos.color = Color.white;
                Gizmos.DrawLine((aConnection.GetFromNode().transform.position + OffSet), (aConnection.GetToNode().transform.position + OffSet));
            }
        }

        Gizmos.DrawWireSphere(transform.position, collisionDetectionRadius);
    }
}