using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AntBehaviour : MonoBehaviour
{
    private int count = 0;
    public float speed;


    // The ACO Controller.
    ACOCON MyACOCON = new ACOCON();

    // Array of possible waypoints.
    [SerializeField] List<GameObject> Waypoints = new List<GameObject>();

    // Connections between nodes.
    private List<Connection> Connections = new List<Connection>();

    // The route generated by the ACO algorithm.
    [SerializeField] private List<Connection> MyRoute = new List<Connection>();

    // Debug line offset.
    private Vector3 OffSet = new Vector3(0, 0.5f, 0);

    // The Start node for any created route.
    public GameObject startNode;
    public List<GameObject> endNode;
    public int currentTarget;


    // performance
    private float gameTimer;
    private float displayGameTimer;

    private float totalDistance = 0;
    private Vector3 previousLoc;

    // time and distance travelled UI
    // public Text GameText;
    // public Text DistanceText;
    //
    // public Text ParcelDrop;
    // public Text AgentSpeed;

    // The max length of a path created by the ACO.
    public int MaxPathLength;


    // The A* manager.
    private AStarManager AStarManager = new AStarManager();

    // Array of waypoint map connections. Represents a path.
    List<Connection> aStarPath = new List<Connection>();
    [SerializeField] private bool haveToReturn = true;


    [SerializeField] private int packageCount = 3;
    private int remaningPackage;

    private void Awake()
    {
        remaningPackage = packageCount;
    }

    private void Start()
    {
        // set count value to 0
        // DropCount = 0;
        // ParcelDropText();

        foreach (GameObject waypoint in Waypoints)
        {
            VisGraphWaypointManager tmpWaypointCon = waypoint.GetComponent<VisGraphWaypointManager>();
            foreach (VisGraphConnection WaypointConNode in tmpWaypointCon.connections)
            {
                Connection aConnection = new Connection();
                aConnection.SetConnection(waypoint, WaypointConNode.ToNode, MyACOCON.GetDefaultPheromone());
                Connections.Add(aConnection);
                AStarManager.AddConnection(aConnection);
            }
        }

        if (remaningPackage > 0)
            GeneratePath(startNode, endNode[0]);
    }

    private void GeneratePath(GameObject _startNode, GameObject _endNode)
    {
        MyRoute = MyACOCON.ACO(100, 5, Waypoints.ToArray(), Connections, _startNode, _endNode, MaxPathLength);

        if (MyRoute == null || MyRoute.Count == 0)
        {
            Debug.LogError("ACO returned an empty route.");
        }
    }

    // Draws debug objects in the editor and during editor play (if option set).
    void OnDrawGizmos()
    {
        // Draw path.
        if (MyRoute.Count > 0)
        {
            //ACO Route
            foreach (Connection aConnection in MyRoute)
            {
                Gizmos.color = Color.white;
                Gizmos.DrawLine((aConnection.GetFromNode().transform.position + OffSet), (aConnection.GetToNode().transform.position + OffSet));
            }
        }
    }

    [SerializeField] private GameObject lastVisitedNode;

    // Update is called once per frame
    void FixedUpdate()
    {
        if (MyRoute.Count <= 0 || packageCount <= 0)
            return;

        if (count < MyRoute.Count)
        {
            if (transform.position != MyRoute[count].GetToNode().transform.position)
            {
                // AgentSpeed.text = "Speed:" + speed.ToString();
                lastVisitedNode = MyRoute[count].GetFromNode();
                transform.position = Vector3.MoveTowards(transform.position, MyRoute[count].GetToNode().transform.position, Time.deltaTime * speed);
                Vector3 relativePos = (MyRoute[count].GetToNode().transform.position) - transform.position;
                transform.rotation = Quaternion.LookRotation(relativePos);
            }
            else
            {
                count++;
            }
        }
        else
        {
            count = 0;
            currentTarget++;
            if (currentTarget <= endNode.Count - 1)
            {
                packageCount--;
                GeneratePath(lastVisitedNode, endNode[currentTarget]);
            }
            else
            {
                MyRoute.Clear();
                if (haveToReturn)
                {
                    haveToReturn = false;
                    aStarPath = AStarManager.PathfindAStar(lastVisitedNode, startNode);
                    MyRoute = aStarPath;
                }
            }
        }
    }

    // public void OnTriggerEnter(Collider other)
    // {
    //     if (other.gameObject.CompareTag("Parcel"))
    //     {
    //         other.gameObject.SetActive(false);
    //         // DropCount = DropCount - 1;
    //         // ParcelDropText();
    //     }
    // }

    // void ParcelDropText()
    // {
    //     ParcelDrop.text = "ParcelDrop:" + DropCount.ToString();
    // }

    // void showPerformance()
    // {
    //     GameText.text = "Time Taken: " + displayGameTimer + " sec";
    // }
    //
    // void showDistance()
    // {
    //     DistanceText.text = "Distance Travelled: " + totalDistance.ToString("f0") + "m";
    // }
}