using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class ACOTester : MonoBehaviour
{
    //Count variable
    private int count = 0;
    private bool reverse = false;

    public float speed;


    private int stop = 0;
    int current;
    private int DropCount = 5;


    // The ACO Controller.
    ACOCON MyACOCON = new ACOCON();

    // Array of possible waypoints.
    [SerializeField] List<GameObject> Waypoints = new List<GameObject>();

    // Connections between nodes.
    private List<Connection> Connections = new List<Connection>();

    // The route generated by the ACO algorithm.
    [SerializeField] private List<Connection> MyRoute = new List<Connection>();

    // Debug line offset.
    private Vector3 OffSet = new Vector3(0, 0.5f, 0);

    // The Start node for any created route.
    public GameObject StartNode;

    public GameObject InitialNode;

    // performance
    private float gameTimer;
    private float displayGameTimer;

    private float totalDistance = 0;
    private Vector3 previousLoc;

    // time and distance travelled UI
    // public Text GameText;
    // public Text DistanceText;
    //
    // public Text ParcelDrop;
    // public Text AgentSpeed;

    public int FoodItems;


    // The max length of a path created by the ACO.
    public int MaxPathLength;

    // The A* manager.
    private AStarManager AStarManager = new AStarManager();

    // Array of possible waypoints.
    List<GameObject> WaypointsP = new List<GameObject>();

    // Array of waypoint map connections. Represents a path.
    List<List<Connection>> ConnectionArray = new List<List<Connection>>();
    List<Connection> pathNodeArray = new List<Connection>();

    // Start is called before the first frame update
    private void Start()
    {
        // set count value to 0
        DropCount = 0;
        // ParcelDropText();

        foreach (GameObject waypoint in Waypoints)
        {
            VisGraphWaypointManager tmpWaypointCon = waypoint.GetComponent<VisGraphWaypointManager>();
            foreach (VisGraphConnection WaypointConNode in tmpWaypointCon.connections)
            {
                Connection aConnection = new Connection();
                aConnection.SetConnection(waypoint, WaypointConNode.ToNode, MyACOCON.GetDefaultPheromone());
                Connections.Add(aConnection);
                AStarManager.AddConnection(aConnection);
            }
        }
        MyRoute = MyACOCON.ACO(100, 20, Waypoints.ToArray(), Connections, StartNode, MaxPathLength);

        if (MyRoute == null || MyRoute.Count == 0)
        {
            Debug.LogError("ACO returned an empty route.");
            return;
        }
        ConnectionArray.Add(AStarManager.PathfindAStar(InitialNode, StartNode));

        foreach (List<Connection> con in ConnectionArray)
        {
            if (con == null || con.Count == 0)
            {
                Debug.Log("Empty Array");
            }

            foreach (Connection acon in con)
            {
                pathNodeArray.Add(acon);
            }
        }
    }

    // Draws debug objects in the editor and during editor play (if option set).
    void OnDrawGizmos()
    {
        // Draw path.
        if (MyRoute.Count > 0)
        {
            //ACO Route
            foreach (Connection aConnection in MyRoute)
            {
                Gizmos.color = Color.white;
                Gizmos.DrawLine((aConnection.GetFromNode().transform.position + OffSet), (aConnection.GetToNode().transform.position + OffSet));
            }

            // //A* path
            // foreach (Connection aConnection in pathNodeArray)
            // {
            //     Gizmos.color = Color.red;
            //     Gizmos.DrawLine((aConnection.GetFromNode().transform.position + new Vector3(0, 1f, 0)), (aConnection.GetToNode().transform.position + new Vector3(0, 1f, 0)));
            // }
        }
    }

    // Update is called once per frame
    void FixedUpdate()
    {
        if (count < pathNodeArray.Count)
        {
            if (!reverse)
            {
                if (transform.position != pathNodeArray[count].GetToNode().transform.position)
                {
                    // AgentSpeed.text = "Speed:" + speed.ToString();
                    transform.position = Vector3.MoveTowards(transform.position, pathNodeArray[count].GetToNode().transform.position, Time.deltaTime * speed);
                    Vector3 relativePos = (pathNodeArray[count].GetToNode().transform.position) - transform.position;

                    transform.rotation = Quaternion.LookRotation(relativePos);
                }
                else
                {
                    count++;
                }
            }
        }
    }

    public void OnTriggerEnter(Collider other)
    {
        if (other.gameObject.CompareTag("Parcel"))
        {
            other.gameObject.SetActive(false);
            DropCount = DropCount - 1;
            // ParcelDropText();
        }
    }

    // void ParcelDropText()
    // {
    //     ParcelDrop.text = "ParcelDrop:" + DropCount.ToString();
    // }

    // void showPerformance()
    // {
    //     GameText.text = "Time Taken: " + displayGameTimer + " sec";
    // }
    //
    // void showDistance()
    // {
    //     DistanceText.text = "Distance Travelled: " + totalDistance.ToString("f0") + "m";
    // }
}